name: CI


# action triggers

on: [push]


# jobs

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup jdk (java 8)
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Prepare gradle
        run: chmod +x gradlew

      - name: Build (gradle)
        run: ./gradlew build

      - name: Upload test reports (on error)
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test-reports
          path: build/reports/tests/test

      - name: Sonarqube analysis
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
        run: ./gradlew sonarqube -Dsonar.branch.name=${GITHUB_REF#refs/heads/}

      - name: Generate checksums
        run: sha256sum build/libs/*.jar > build/libs/checksums.sha256

      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build-${{ github.run_id }}
          path: build/libs